name: Build

on:
  push:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone tree
      uses: actions/checkout@v2
    - name: Build
      run: |
        COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 \
        docker compose build \
          frontend \
          angr \
          ghidra \
          reko \
          retdec \
          snowman
