name: Build

on:
  push:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone tree
      uses: actions/checkout@v2
    - name: Build
      run: |
        COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 \
        docker compose build \
          frontend \
          angr \
          ghidra \
          r2dec \
          reko \
          retdec \
          snowman
    - name: Test
      run: |
        docker compose up --detach \
          frontend \
          angr \
          ghidra \
          r2dec \
          reko \
          retdec \
          snowman
        sleep 5
        python3 -m pip install requests
        python3 -m unittest tests/test.py
        docker compose down
